name: End to End Tests

on:

  push:
    branches: [main]

  pull_request:

permissions:

  contents: read

jobs:

  tests:
    name: End to End Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          # @todo uncomment after verified to be working as expected
          # - '7.4'
          # - '8.0'
          # - '8.1'
          - '8.2'
        # @todo this needs to be used in the refresh-test-dependencies script
        # dependencies:
        #   - ''
        #   - '--prefer-lowest'
        wordpress:
          - 'latest'
        # WP 5.1 was arbitrarily chosen because it was released around the time of PHP 7.4
        # @todo uncomment after verified to be working as expected
        # include:
        #   - php: '7.4'
        #     wordpress: '5.1'
        #   - php: '8.2'
        #     wordpress: '5.1'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Prepare WP environment overrides
        run: |
          wp-env/set-versions.sh ${{ matrix.php }} ${{ matrix.wordpress }}
          cat .wp-env.override.json | jq

      - name: Start WP environment
        run: |
          wp-env/prepare.sh
          sed -i "s/dev-master/dev-$GITHUB_SHA/" tests/fixtures/twr-test-plugin/composer.json
          wp-env/refresh-test-dependencies.sh
          wp-env/print-config.js | jq

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer update --ansi --no-interaction --no-progress --prefer-dist

      - name: Run e2e tests
        run: composer run btest

      # @todo uncomment after verified to be working as expected
      # - name: Run e2e tests with cache enabled
      #   run: composer run cbtest
